name: Workflow C calls Workflow B from reusable-repo-2.

on:
  workflow_dispatch:
    inputs:
      input_message:
        description: 'Message to pass to Workflow B'
        required: true

jobs:
  call-workflow-b:
    uses: owner/reusable-repo-2/.github/workflows/workflow-b.yml@main  # Correct path to the reusable workflow in another repo
    with:
      input_message: ${{ github.event.inputs.input_message }}  # Pass input from Workflow C to Workflow B
